import type { AgentTeam, Client, MissionRequest } from "./contracts";

/**
 * Example marketplace population: registered agent TEAMS (supply) and CLIENTS
 * who post MISSION REQUESTS with a budget (demand). Deterministic seed data for
 * the demo — reputation numbers stand in for what would be derived from each
 * team's on-chain mission history.
 */

export const SEED_TEAMS: AgentTeam[] = [
  {
    id: "team-redteam-labs",
    name: "RedTeam Labs",
    domains: ["security"],
    description: "Full-stack offensive security fleet — recon through validated exploitation and reporting.",
    orchestratorModel: "llama-3.3-70b",
    roles: ["attack-surface", "web-scanner", "network-scanner", "auth-tester", "injection", "exploit-validator", "secrets-hunter", "report-writer"],
    workerModels: {
      "attack-surface": "llama-3.1-8b", "web-scanner": "venice-uncensored", "network-scanner": "venice-uncensored",
      "auth-tester": "venice-uncensored", injection: "qwen-2.5-coder", "exploit-validator": "venice-uncensored",
      "secrets-hunter": "venice-uncensored", "report-writer": "llama-3.3-70b",
    },
    priceKasPerMission: 10,
    reputation: { missionsCompleted: 128, successRate: 0.95, budgetAdherence: 0.97, humanApprovalRate: 0.09, rating: 4.8 },
    registeredTxid: null,
    tags: ["OWASP", "web", "network", "pentest"],
  },
  {
    id: "team-dataforge",
    name: "DataForge",
    domains: ["data"],
    description: "Data pipeline QA team — ingestion, validation, entity resolution and reporting.",
    orchestratorModel: "llama-3.3-70b",
    roles: ["data-ingest", "data-validator", "dedupe", "data-report"],
    workerModels: { "data-ingest": "llama-3.1-8b", "data-validator": "qwen-2.5-coder", dedupe: "qwen-2.5-coder", "data-report": "llama-3.3-70b" },
    priceKasPerMission: 6,
    reputation: { missionsCompleted: 340, successRate: 0.93, budgetAdherence: 0.99, humanApprovalRate: 0.03, rating: 4.6 },
    registeredTxid: null,
    tags: ["ETL", "validation", "quality"],
  },
  {
    id: "team-researchops",
    name: "ResearchOps",
    domains: ["research"],
    description: "Research synthesis team — multi-source search, deep reading, adversarial citation checks.",
    orchestratorModel: "gpt-oss-120b",
    roles: ["searcher", "reader", "synthesizer", "citation-checker"],
    workerModels: { searcher: "llama-3.1-8b", reader: "llama-3.3-70b", synthesizer: "gpt-oss-120b", "citation-checker": "venice-uncensored" },
    priceKasPerMission: 5,
    reputation: { missionsCompleted: 92, successRate: 0.97, budgetAdherence: 0.96, humanApprovalRate: 0.02, rating: 4.9 },
    registeredTxid: null,
    tags: ["synthesis", "citations", "verify"],
  },
  {
    id: "team-sre-sentinels",
    name: "SRE Sentinels",
    domains: ["devops"],
    description: "Incident response team — triage, diagnosis, gated remediation and postmortems.",
    orchestratorModel: "llama-3.3-70b",
    roles: ["incident-triage", "diagnoser", "remediator", "postmortem"],
    workerModels: { "incident-triage": "llama-3.1-8b", diagnoser: "venice-uncensored", remediator: "qwen-2.5-coder", postmortem: "llama-3.3-70b" },
    priceKasPerMission: 12,
    reputation: { missionsCompleted: 210, successRate: 0.91, budgetAdherence: 0.94, humanApprovalRate: 0.14, rating: 4.7 },
    registeredTxid: null,
    tags: ["SRE", "incident", "remediation"],
  },
  {
    id: "team-ledgerbalance",
    name: "LedgerBalance",
    domains: ["finance"],
    description: "Financial operations team — reconciliation, anomaly detection and reporting.",
    orchestratorModel: "gpt-oss-120b",
    roles: ["reconciler", "anomaly-detector", "finance-report"],
    workerModels: { reconciler: "qwen-2.5-coder", "anomaly-detector": "venice-uncensored", "finance-report": "llama-3.3-70b" },
    priceKasPerMission: 8,
    reputation: { missionsCompleted: 76, successRate: 0.9, budgetAdherence: 0.98, humanApprovalRate: 0.06, rating: 4.5 },
    registeredTxid: null,
    tags: ["reconciliation", "anomaly", "audit"],
  },
];

export const SEED_CLIENTS: Client[] = [
  { id: "client-sam", name: "Sam Okafor", org: "Northwind Group", initials: "SO" },
  { id: "client-priya", name: "Priya Raman", org: "Helios Data", initials: "PR" },
  { id: "client-marc", name: "Marc Devries", org: "Atlas Insights", initials: "MD" },
  { id: "client-lena", name: "Lena Costa", org: "Voltstream", initials: "LC" },
];

const NOW = "2026-07-03T09:00:00.000Z";

export const SEED_MISSION_REQUESTS: MissionRequest[] = [
  {
    id: "req-web-audit",
    clientId: "client-sam",
    title: "External attack-surface audit — Juice Shop (staging)",
    domain: "security",
    objective: "Map, scan, validate and report the attack surface of the staging web app. Passive recon; active exploitation gated.",
    target: "juice-shop.internal.staging",
    budgetKas: 12,
    deadline: "2026-07-10",
    policy: { perAgentBudgetCapKas: 4, humanApprovalThresholdKas: 3, highImpactActions: ["active_exploit"] },
    status: "open",
    assignedTeamId: null,
    createdAt: NOW,
  },
  {
    id: "req-data-qa",
    clientId: "client-priya",
    title: "Customer data pipeline QA",
    domain: "data",
    objective: "Validate schema, integrity and dedup the nightly customer ingest; report anomalies.",
    target: "warehouse.helios.internal",
    budgetKas: 8,
    deadline: "2026-07-08",
    policy: { perAgentBudgetCapKas: 3, humanApprovalThresholdKas: 2, highImpactActions: [] },
    status: "open",
    assignedTeamId: null,
    createdAt: NOW,
  },
  {
    id: "req-research",
    clientId: "client-marc",
    title: "Competitive landscape synthesis — agent infra",
    domain: "research",
    objective: "Search, read and synthesize the 2026 agent-infrastructure landscape with verified citations.",
    target: "public sources",
    budgetKas: 6,
    deadline: "2026-07-12",
    policy: { perAgentBudgetCapKas: 2, humanApprovalThresholdKas: 2, highImpactActions: [] },
    status: "recruiting",
    assignedTeamId: null,
    createdAt: NOW,
  },
  {
    id: "req-incident",
    clientId: "client-lena",
    title: "Payment API latency incident — drill",
    domain: "devops",
    objective: "Triage, diagnose and propose remediation for the checkout latency spike. Prod changes gated.",
    target: "checkout-api.voltstream",
    budgetKas: 15,
    deadline: "2026-07-05",
    policy: { perAgentBudgetCapKas: 5, humanApprovalThresholdKas: 3, highImpactActions: ["prod_change"] },
    status: "open",
    assignedTeamId: null,
    createdAt: NOW,
  },
  {
    id: "req-recon",
    clientId: "client-sam",
    title: "Quarterly account reconciliation",
    domain: "finance",
    objective: "Reconcile Q2 subledgers against the GL, flag breaks and anomalies, produce an audit report.",
    target: "gl.northwind.internal",
    budgetKas: 10,
    deadline: "2026-07-15",
    policy: { perAgentBudgetCapKas: 4, humanApprovalThresholdKas: 3, highImpactActions: [] },
    status: "open",
    assignedTeamId: null,
    createdAt: NOW,
  },
];
