name: Next.js CI

on:
  push:
    branches: ["main", "integration"]
  pull_request:
    branches: ["main", "integration"]

jobs:
  ci:
    uses: NerionSoft/nerionsoft-cicd/.github/workflows/reusable-nextjs-ci.yml@main
    with:
      run-sonar: true
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-project-name: ${{ vars.SONAR_PROJECT_NAME }}
    secrets:
      CI_DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}
      CI_BETTER_AUTH_SECRET: ${{ secrets.CI_BETTER_AUTH_SECRET }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}

    # Default config:
    # with:
    #   node-version: "24"
    #   run-lint: true
    #   run-format: true
    #   run-typecheck: true
    #   run-test: true
    #   run-build: true
    #   run-e2e: true
    #   run-sonar: false
    #   sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    #   sonar-project-name: ${{ vars.SONAR_PROJECT_NAME }}
    # secrets:
    #   CI_DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}
    #   CI_BETTER_AUTH_SECRET: ${{ secrets.CI_BETTER_AUTH_SECRET }}
    #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #   SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}
