name: Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: NerionSoft/nerionsoft-cicd/.github/workflows/reusable-release.yml@main
    # with:
    #   release-type: "node"
    #   update-floating-tags: true
